### ISSUE TITLE
No system log for hvm ami on ec2

### ISSUE THREAD

**Issue by altaurog** [andsens/bootstrap-vz#136]
I'm not getting anything in the system log on EC2 with the hvm ami.
I've tried the hvm ami in other regions as well, with no success.
I had the same experience with an earlier release several months ago.
I have tried with various instance types.  Instance checks were ok.
I waited over half an hour.  I used standard root ebs device only.
When I try "Get System Log" on the AWS console, it just shows a blank
black box.

I blindly accepted the fingerprint reported by ssh and was in fact
able to log in to the machine.  I don't want to do that, though.

Could it be the console isn't going to the right place on the hvm image?

**Comment by dukedougal** [comment]
@john-pierce you say "The console on HVM images needs to be set to ttyS0." Is there a reason for this? Does this mean the EC2 system log does not work with VGA on HVM?  I've searched extensively for information to understand this but turned up almost nothing except your info above. thanks

**Comment by john-pierce** [comment]
@dukedougal I have no idea why.
