### ISSUE TITLE
msdos partition type incorrect for swap partition (Linux)

### ISSUE THREAD

**Issue by olberger** [andsens/bootstrap-vz#142]
fdisk -l inside a virtualbox/vagrant VM show all 3 partitions types Linux, whereas only / and /boot should.
swap should be 82 and not 83, I think.

Hope this helps.

**Comment by myhro** [comment]
My intuition in the last comment and Olivier's tip were right. Fixed in dev as 3131558:

Before:

```
vagrant@localhost:~$ sudo fdisk -l

Disk /dev/sda: 2281 MB, 2281701376 bytes
255 heads, 63 sectors/track, 277 cylinders, total 4456448 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000c6795

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1            4096      262144      129024+  83  Linux
/dev/sda2   *      262145     4456447     2097151+  83  Linux
```

After:

```
vagrant@localhost:~$ sudo fdisk -l

Disk /dev/sda: 2281 MB, 2281701376 bytes
255 heads, 63 sectors/track, 277 cylinders, total 4456448 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000d7426

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1            4096      262144      129024+  82  Linux swap / Solaris
/dev/sda2   *      262145     4456447     2097151+  83  Linux
```

**Comment by andsens** [comment]
Wow, that `fs-type` option for `mkpart` is one weird fella:
> fs-type must be one of these supported file systems:
* ext2
* fat16, fat32
* hfs, hfs+, hfsx
* linux-swap
* NTFS
* reiserfs
* ufs
* btrfs

It's a potpourri of filesystems they seem to have just thrown together.

Nice going on fixing this @myhro, thank you!

**Comment by myhro** [comment]
> Wow, that `fs-type` option for `mkpart` is one weird fella:
> It's a potpourri of filesystems they seem to have just thrown together.

I'd like to know the history of [these hexadecimal numbers][sfdisk-types] (`sfdisk -T` output) that identify partition types. I've thought that `ext2` (which is `83/Linux`) was valid for all Linux filesystems, but this `btrfs` option makes it a little bit confusing. Maybe it's an alias to `83` as well? Just wondering, this is actually not a big deal. :-)

You're welcome, Anders.

[sfdisk-types]: https://gist.githubusercontent.com/anonymous/a1b6218c96be3df2e179/raw/f10ac8425b0cb9927f1688960fdaf691f641f08b/sfdisk.txt
