### ISSUE TITLE
Documentation missing a required python dependency

### ISSUE THREAD

**Issue by drywheat** [andsens/bootstrap-vz#152]
This docs indicate that **termcolor**, **fysom** and **jsonschema** are required python dependencies but it fails to mention **docopt**, which is used in the `main()` function.

```python
# bootstrapvz/base/main.py, +36
def get_opts():
        """Creates an argument parser and returns the arguments it has parsed
        """
        from docopt import docopt
        usage = """bootstrap-vz
```

**Comment by arthurlogilab** [comment]
bumped into this bug too

**Comment by myhro** [comment]
I guess we'll need to add `Pyro4` also, as I can't build anything on `wip-integration-testing` without it. I'm not really sure if it is need only for testing (and correcting the `import`s will fix that).

**Comment by andsens** [comment]
Huh. That is interesting. I guess something from the `remote` package is leaking into the `base` package.

**Comment by andsens** [comment]
Aha. It's the `get_all_classes` function that is used to find all tasks. It traverse into the remote package as well.

**Comment by myhro** [comment]
Thank you, Anders. Now I could execute it without `Pyro4`. :-)
