### ISSUE TITLE
Ansible Plugin

### ISSUE THREAD

**Issue by Rory-Finnegan** [andsens/bootstrap-vz#183]
I wrote an Ansible [plugin](https://github.com/Rory-Finnegan/bootstrap-vz/tree/ansible) for running playbooks on a build, would anybody else be interested in this?

**Comment by andsens** [comment]
Hah. That is awesome, this has been on my todo list for a while, since I'm using ansible myself. I'd definitely be interested in this!

**Comment by Rory-Finnegan** [comment]
Alright, I'll make a pull request, but I'm not sure where I should put the documentation on how to use it. `docs/plugins/ansible.rst`?

**Comment by andsens** [comment]
For the time being we're using the `gh-pages-dev` branch, but honestly it's way too much of a hassle. I'm thinking of converting everything into the GH wiki, it's way easier to maintain and doesn't require html skills. Maybe I'll convert it all to the wiki tomorrow, then you can just add it there.

sooo ask me again in 24h? :-)

**Comment by andsens** [comment]
[Here you go](https://github.com/andsens/bootstrap-vz/wiki/dev_Home) :-)

**Comment by Rory-Finnegan** [comment]
Thanks, sorry for the late response.  I've made a merge request for the ansible plugin [here](https://github.com/andsens/bootstrap-vz/pull/194). I'll update the dev_Plugins wiki when it is merged.

**Comment by jszwedko** [comment]
Should this be closed given #108 and the wiki having been updated?

**Comment by andsens** [comment]
Woops, yeah. Closing.
