### ISSUE TITLE
README.md does not mention brancing model

### ISSUE THREAD

**Issue by EmmanuelKasper** [andsens/bootstrap-vz#184]
I was hit bit #121 on the bootstrap-vz debian package of Debian 8 and I cloned the git repo to see if the problem was fix upstream.
This bug is fixed , but  in the developmenet branch of bootstrap-vz, not in the master branch ( the default when you git pull)
It took me some time to try to reproduce the bug and think of a fix, before noticing the bug was fixed in a another bramch. Maybe we could add something like in the README.md ( of both branches !) ? 

Installation
-------------
bootstrap-vz has a `master` branch for stable releases and a `development`  for, well, development.
After checking out the branch of your choise, installation is done by calling
    python setup.py install

**Comment by andsens** [comment]
Yes, will definitely add this when I get home. thanks!
Sorry about the wasted time :-(

**Comment by andsens** [comment]
Woops, referenced the wrong issue in the commit msg, it's fixed though :-)
