### ISSUE TITLE
alternative network configuration

### ISSUE THREAD

**Issue by jwendell** [andsens/bootstrap-vz#191]
Currently the network configuration - more specifically /etc/network/interfaces file - is kind of hard coded through the file common/tasks/network-configuration.yml

I need my image to have a different configuration. So, I'm wondering what's the best option to overwrite this...

Perhaps writing a plugin where we can specify an alternative network-configuration.yml file? Or it could accept directly the configuration via its parameters?

**Comment by andsens** [comment]
I think we need to be careful not to venture into the domain of configuration management, there are excellent tools out there for that purpose (ansible, salt, chef, puppet - to name a few). bootstrap-vz also has plugins for most of these (an ansible plugin is on the way).

NIC configuration is pretty close to that invisible line and unless it is impossible to contact an instance after startup when configured in a specific way I think we should refrain from crossing that border.

The network configuration is written by appending to `/etc/network/interfaces`, so you could theoretically use the `image_command` plugin to do the same (assuming the `eth0` config should be kept). However, the challenge here is you don't know in which order the tasks will be executed - I have been thinking about creating a new phase after `system_modification` called `user_modification`, where things like config management plugins, the `file_copy` plugin or the `image_command` plugin can run.

**Comment by jwendell** [comment]
I was thinking in something really simple, like having 2 entries (eth0 and eth1) in that file.
In my specific case, I'm launching a machine with 2 network cards, that's why I need to overwrite the default configuration.

Is there anything better to my situation?
Thanks.

**Comment by jszwedko** [comment]
@andsens I like the idea of guaranteeing the phase (or adding a new one) during which `image_command`s will be run and doing this sort of configuration there.

**Comment by andsens** [comment]
Yup, created #204 and closing this one.

**Comment by andsens** [comment]
FYI f1010b11aef6fd793302e85abbfdeb38af1b8ea0 added support for multiple ENIs.
