### ISSUE TITLE
extlinux install fails in development

### ISSUE THREAD

**Issue by Rory-Finnegan** [andsens/bootstrap-vz#196]
When I try to build an hvm image using the extlinux bootloader I get this
```
Installing extlinux
Executing: chroot /target/d8357bc2/root dd bs=440 count=1 if=/usr/lib/extlinux/mbr.bin of=/dev/xvdi
dd: failed to open ‘/usr/lib/extlinux/mbr.bin’: No such file or directory
```
during installation.

**Comment by andsens** [comment]
[Fixed in wip-integration-testing](https://github.com/andsens/bootstrap-vz/blob/wip-integration-testing/bootstrapvz/common/tasks/extlinux.py#L103). I'll be merging that branch pretty soon, just need to get ec2 testing up and running.

**Comment by Rory-Finnegan** [comment]
Thanks for the link. I'm not sure if this should be a separate issue, but it looks like the ssh server might not be getting installed or doesn't start for AWS EBS HVM images. I've verified that I'm using the correct key and that it has to correct permissions, but whenever I try to bring up HVM builds I get the following output when trying to ssh in.
```
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: bogus-key.pem ((nil))
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: bogus-key.pem
debug1: read PEM private key done: type RSA
debug3: sign_and_send_pubkey: RSA XX:XX:XX: ...
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
```
Any thoughts?

The most recent commit I'm using off of wip-integration-testing is [da6f9291](https://github.com/andsens/bootstrap-vz/commit/da6f9291353df60983ff6a959228967c5eb5954e)

**Comment by andsens** [comment]
Hm, are you logging in as root or admin? Could you post the manifest in a gist and the ssh command?

**Comment by Rory-Finnegan** [comment]
Here's the [gist](https://gist.github.com/Rory-Finnegan/6ab7cf05c4e2251c1f37). I've included the AWS boot log if it helps, but I don't see anything about the ssh failing.

**Comment by andsens** [comment]
Huh, that is indeed weird, I don't see anything out of the ordinary. Could you post the bootstrap log as well?

**Comment by Rory-Finnegan** [comment]
Have the ec2 start scripts changed recently? Also, do you have any suggestions for how debug this?

**Comment by andsens** [comment]
Fiddle with the startup script. Make sure it actually runs (i.e. print something to the console/log). Output the data returned from the metadata URL. Figure out if dependency based booting has recently changed because of systemd.

**Comment by Rory-Finnegan** [comment]
Looks, like something during the boot steps is overwriting the /root/.ssh/authorized_keys files, cause I was able to login once and then when I tried to login from another terminal later the error came up again. From my original ssh session I noticed that the file was empty. Also, looks like the `logger` output in the ec2 start scripts doesn't show up in the AWS boot log.

**Comment by myhro** [comment]
Hi @Rory-Finnegan,

Does this problem persists? Should we rename the issue or can we close it?

**Comment by Rory-Finnegan** [comment]
Yeah, I haven't built an image in a while, but this is probably safe to close. If I run into the issue again I'll just reopen.
