### ISSUE TITLE
ed25519 SSH host key not generated.

### ISSUE THREAD

**Issue by andsens** [andsens/bootstrap-vz#197]
Copypasta from debianc-cloud mailing list below (reported by Santiago Vila <sanvila@unex.es>):

Greetings. I'm testing the Amazon Free Tier since a few days, and I've
discovered a very simple bug in the above image (ami-5e615343).

The file /etc/ssh/sshd_config says:

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

but the last one (ed25519) does not actually exist.

As a result, messages like this one may be found in /var/log/auth.log:

[...] sshd[4859]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key

The simple workaround is "dpkg-reconfigure openssh-server" but we
might better fix this in the images (cloud-init maybe, I'm completely
new to this).

**Comment by myhro** [comment]
I've tried to reproduce it bootstrapping and booting an `wheezy` GCE instance and I'm unable to confirm it.

Those are the output for the following steps:

Bootstraping:

    (...)
    Setting up openssh-server (1:6.0p1-4+deb7u2) ...
    Creating SSH2 RSA key; this may take some time ...
    Creating SSH2 DSA key; this may take some time ...
    Creating SSH2 ECDSA key; this may take some time ...
    (...)

Booting:

    (...)
    Apr 11 11:20:54 myhro-bvz-test first-boot: Running first-boot
    regenerate-host-keys: Regenerating SSH Host Keys for:  (previously ).
    Apr 11 11:20:54 myhro-bvz-test regenerate-host-keys: Regenerating SSH Host Keys for:  (previously ).
    regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_dsa_key
    Apr 11 11:20:54 myhro-bvz-test regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_dsa_key
    regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_ecdsa_key
    Apr 11 11:20:54 myhro-bvz-test regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_ecdsa_key
    regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_rsa_key
    Apr 11 11:20:54 myhro-bvz-test regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_rsa_key
    regenerate-host-keys: starting sshd
    Apr 11 11:20:54 myhro-bvz-test regenerate-host-keys: starting sshd
    [....] Starting OpenBSD Secure Shell server: sshdApr 11 11:20:54 myhro-bvz-test sshd[1934]: Server listening on 0.0.0.0 port 22.
    Apr 11 11:20:54 myhro-bvz-test sshd[1934]: Server listening on :: port 22.
    (...)

First login after boot:

    myhro@myhro-bvz-test:~$ ls -lh /etc/ssh/ssh_host_*
    -rw------- 1 root root  668 Apr 11 11:20 /etc/ssh/ssh_host_dsa_key
    -rw-r--r-- 1 root root  609 Apr 11 11:20 /etc/ssh/ssh_host_dsa_key.pub
    -rw------- 1 root root  223 Apr 11 11:20 /etc/ssh/ssh_host_ecdsa_key
    -rw-r--r-- 1 root root  181 Apr 11 11:20 /etc/ssh/ssh_host_ecdsa_key.pub
    -rw------- 1 root root 1.7K Apr 11 11:20 /etc/ssh/ssh_host_rsa_key
    -rw-r--r-- 1 root root  401 Apr 11 11:20 /etc/ssh/ssh_host_rsa_key.pub

But when I do look for which keys are supposed to be present...

    myhro@myhro-bvz-test:~$ grep HostKey /etc/ssh/sshd_config 
    # HostKeys for protocol version 2
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_dsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key

The `ed25519` key isn't there.

**Comment by myhro** [comment]
Oh... Looks like I've missed an important detail: [the `ami-5e615343` image is a `jessie` one][jessie-amis]. Of course I wouldn't ever be able to confirm this: the `openssh-server` 6.0, which is the version that comes with `wheezy`, does not supports ed25519 keys, as this [was implemented only on the 6.5 version][openssh-65]:

> * ssh(1), sshd(8): Add support for Ed25519 as a public key type.
>    Ed25519 is a elliptic curve signature scheme that offers
>    better security than ECDSA and DSA and good performance. It may be
>    used for both user and host keys.

[jessie-amis]: https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie
[openssh-65]: http://www.openssh.com/txt/release-6.5

**Comment by myhro** [comment]
Now I can say that I'm unable to confirm this. I've built a `jessie` image to test #165 and here's the result:

```
vagrant@localhost:~$ grep HostKey /etc/ssh/sshd_config 
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
vagrant@localhost:~$ ls -lh /etc/ssh/ssh_host_*
-rw------- 1 root root  668 Apr 25 16:41 /etc/ssh/ssh_host_dsa_key
-rw-r--r-- 1 root root  594 Apr 25 16:41 /etc/ssh/ssh_host_dsa_key.pub
-rw------- 1 root root  227 Apr 25 16:41 /etc/ssh/ssh_host_ecdsa_key
-rw-r--r-- 1 root root  166 Apr 25 16:41 /etc/ssh/ssh_host_ecdsa_key.pub
-rw------- 1 root root  419 Apr 25 15:52 /etc/ssh/ssh_host_ed25519_key
-rw-r--r-- 1 root root  108 Apr 25 15:52 /etc/ssh/ssh_host_ed25519_key.pub
-rw------- 1 root root 1.7K Apr 25 16:41 /etc/ssh/ssh_host_rsa_key
-rw-r--r-- 1 root root  386 Apr 25 16:41 /etc/ssh/ssh_host_rsa_key.pub
```

Maybe that was a temporary problem (with `cloud-init`?) back then, but it doesn't look to be a problem right now (unless it's specific to EC2). Can we close this issue?

**Comment by andsens** [comment]
Closing this on my own accord, since it was unconfirmed to begin with...
