### ISSUE TITLE
Remaining work for `wip-integration`?

### ISSUE THREAD

**Issue by jszwedko** [andsens/bootstrap-vz#202]
I'd love to help out with finishing the `wip-integration` branch to enable testing, but I'm not sure where to start. It'd be great if we could create Github issues and tag them or somehow else document.

**Comment by andsens** [comment]
If I get the basics for ec2 up and running tonight, the next step will be testing, lots and lots of testing.
Right now I'm only checking pvgrub 64 bit combinations, but we need to check all combinations of the following dimensions.
* boot: pvgrub, extlinux (hvm), grub (hvm)
* backing: s3, ebs
* arch: 32bit, 64bit
* release: squeeze, wheezy, jessie
* partitiontable: unpartitioned, gpt, msdos

That makes for 108 combinations in all.

Oh, and that's just for ec2 :-) (but we'll keep it at vbox and ec2 for now)

**Comment by andsens** [comment]
Yup. Things are working now! I'm running the [ec2 tests](https://github.com/andsens/bootstrap-vz/blob/fa269588fce3e6932535afd8497f776279b64fa1/tests/integration/ec2.py) right now. You can make a new suite for hvm or s3 images if you like and test those.

**Comment by jszwedko** [comment]
:smile: thank you -- if I get some time I'll give that shot. Closing this issue for now.
