### ISSUE TITLE
Add prebootstrapped example 

### ISSUE THREAD

**Issue by jniggemann** [andsens/bootstrap-vz#208]
It'd be a good idea to have an example for the prebootstrapped plugin in the documentation.

**Comment by andsens** [comment]
In what way? I don't think simply showing an example configuration would help. You're thinking of a real-world scenario description, correct?

**Comment by jniggemann** [comment]
Yep, what I initially meant was an real-world example. But now that I think about it... perhaps I opened this issue too soon... Given the target audience of bootstrap-vz is most probably very well versed in system administration, scripting, ... , the existing documentation is probably sufficient...
