### ISSUE TITLE
Creation of disk uuid link that already exists

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#210]
I was trying to build the KVM-virtio and VirtualBox-Vagrant manifests using the `wip-integration-testing` branch, but both of them failed showing same error:

    Traceback (most recent call last):
      File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
        tasklist.run(info=bootstrap_info, dry_run=dry_run)
      File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 38, in run
        task.run(info)   
      File "/root/bootstrap-vz/bootstrapvz/common/tasks/grub.py", line 51, in run
        p_map.root.device_path = info.volume.device_path
      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
        self.gen.next()  
      File "/root/bootstrap-vz/bootstrapvz/common/fs/__init__.py", line 30, in unmounted
        p_map.map(volume)
      File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 61, in map
        self.fsm.map(volume=volume)
      File "/root/.virtualenvs/bvz/local/lib/python2.7/site-packages/fysom/__init__.py", line 240, in fn
        if self._before_event(e) is False:
      File "/root/.virtualenvs/bvz/local/lib/python2.7/site-packages/fysom/__init__.py", line 274, in _before_event
        return getattr(self, fnname)(e)
      File "/root/bootstrap-vz/bootstrapvz/base/fs/partitionmaps/abstract.py", line 86, in _before_map
        self.partitions[p_idx].map(partition_path)
      File "/root/bootstrap-vz/bootstrapvz/base/fs/partitions/base.py", line 74, in map
        self.fsm.map(device_path=device_path)
      File "/root/.virtualenvs/bvz/local/lib/python2.7/site-packages/fysom/__init__.py", line 240, in fn
        if self._before_event(e) is False:
      File "/root/.virtualenvs/bvz/local/lib/python2.7/site-packages/fysom/__init__.py", line 274, in _before_event
        return getattr(self, fnname)(e)
      File "/root/bootstrap-vz/bootstrapvz/base/fs/partitions/base.py", line 118, in _before_map
        self.link_uuid() 
      File "/root/bootstrap-vz/bootstrapvz/base/fs/partitions/base.py", line 88, in link_uuid
        os.symlink(self.device_path, self.disk_by_uuid_path)
    OSError: [Errno 17] File exists

Commenting lines [88][line-88] and [92][line-92] on `bootstrapvz/base/fs/partitions/base.py`, skiping link creation and deletion, solved the problem.

Investigating the issue, I've noticed the code that does this was added yesterday by 03efa0f. As I'm using an `wheezy` machine on Digital Ocean, I don't really know if the kernel is different from stock (I'll ask the Google guys if I can still use their GCE project to do this), but I guess this is not the problem. What looks like is that this workaround is not needed for the current `stable`.

What system are you using to develop/build/test, Anders?

[line-88]: https://github.com/andsens/bootstrap-vz/blob/wip-integration-testing/bootstrapvz/base/fs/partitions/base.py#L88
[line-92]: https://github.com/andsens/bootstrap-vz/blob/wip-integration-testing/bootstrapvz/base/fs/partitions/base.py#L92

**Comment by andsens** [comment]
Huh, that is really interesting. I'm bootstrapping on wheezy as well. How come the uuid links get created on your machine? I guess this linking business needs to be a little more sophisticated.

**Comment by andsens** [comment]
What does `dpkg-query -W kpartx` tell you?

**Comment by myhro** [comment]
The same thing happened on a GCE instance running `wheezy`, so it's not Digital Ocean's fault.

> What does `dpkg-query -W kpartx` tell you?

    [root@myhro-bvz:~]# dpkg-query -W kpartx
    kpartx  0.4.9+git0.4dfdaf2b-7~deb7u2

**Comment by andsens** [comment]
Huh, I've got the same version. Do you have a `/lib/udev/rules.d/60-kpartx.rules` file, and if so, what does it look like?

**Comment by myhro** [comment]
> Do you have a `/lib/udev/rules.d/60-kpartx.rules` file, and if so, what does it look like?

Yes I do:

    #
    # persistent links for device-mapper devices
    # only hardware-backed device-mapper devices (ie multipath, dmraid,
    # and kpartx) have meaningful persistent device names
    #

    KERNEL!="dm-*", GOTO="kpartx_end"
    ACTION=="remove", GOTO="kpartx_end"

    # This is a temporary hack until Debian's dmsetup properly supports "dmsetup
    # export". For more information see: #434241, #487881, #493078
    IMPORT{program}="dmsetup_env %M %m"

    ENV{DM_TABLE_STATE}!="LIVE", GOTO="kpartx_end"

    ENV{DM_UUID}=="?*", IMPORT{program}=="kpartx_id %M %m $env{DM_UUID}"

    OPTIONS="link_priority=50"

    # Create persistent links for multipath tables
    ENV{DM_UUID}=="mpath-*", \
            SYMLINK+="disk/by-id/$env{DM_TYPE}-$env{DM_NAME}"

    # Create persistent links for partitions
    ENV{DM_PART}=="?*", \
            SYMLINK+="disk/by-id/$env{DM_TYPE}-$env{DM_NAME}-part$env{DM_PART}"

    # Create dm tables for partitions
    ENV{DM_STATE}=="ACTIVE", ENV{DM_UUID}=="mpath-*", \
            RUN+="/sbin/kpartx -u -p -part /dev/$name"

    LABEL="kpartx_end"

**Comment by andsens** [comment]
WTF? Now I'm genuinely confused. This script obvioulsy doesn't create the UUID links, so how do they magically appear?!  
I think I'll just do a check for its existence instead and the not link it if it's already there... Problem is, I'll then have to remember whether the code created it or kpartx. Ah yes, the joy of hacks....

**Comment by myhro** [comment]
>  Ah yes, the joys of hacks....

Haha. It wouldn't be that fun if we don't need them. :-)

I'm more interested in finding out why you are needing this workaround, Anders. I mean: how your `wheezy` machine diverges from the ones that I've tested.

**Comment by andsens** [comment]
Maybe I should try bootstrapping from a fresh AMI, if that fixes the problem I'll just remove the hack completely. Sorry for taking so long to answer btw., working on [this](http://bootstrap-vz.readthedocs.org/en/full-sphinx-documentation/) right now. I'm combining all docs into sphinx, and killing the wiki and github pages - this way the documentation always matches what's online - and the plugins docs can now reside as READMEs in the plugin folders :-)

**Comment by myhro** [comment]
> Maybe I should try bootstrapping from a fresh AMI, if that fixes the problem I'll just remove the hack completely.

Or a machine on a different provider. Are you using Vagrant as well?

> Sorry for taking so long to answer btw.

No problem, I was AFK also.

> I'm combining all docs into sphinx, and killing the wiki and github pages - this way the documentation always matches what's online - and the plugins docs can now reside as READMEs in the plugin folders :-)

This is **really** nice. Well done, Anders (as always)!

I'm just worried about the conflicts that could happen when we merge all the current branches. Maybe we should discuss this on another channel (or issue), but do you plan to keep the same `master`/`development` separation after the next big merge?

**Comment by andsens** [comment]
Yup, I can't reproduce the original bug on a newly bootstrapped machine, reverted the commit....
