### ISSUE TITLE
Sparse file is created on the current directory

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#212]
When bootstrapping a GCE image, I've noticed that it creates a sparse file named `create` on the current directory where `bootstrap-vz` is called:

    [root@myhro-bvz:~/bootstrap-vz]# ls -lh create
    ls: cannot access create: No such file or directory
    [root@myhro-bvz:~/bootstrap-vz]# ./bootstrap-vz manifests/gce.manifest.yml
    (...)
    [root@myhro-bvz:~/bootstrap-vz]# ls -lh create
    -rw-r--r-- 1 root root 10G Apr 11 10:30 create
    [root@myhro-bvz:~/bootstrap-vz]# du -sh create 
    0       create

I haven't found out why this file is created or even if it has been used at all.

**Comment by myhro** [comment]
Looks like it's not just GCE, as KVM does that also.

**Comment by andsens** [comment]
What the...? Any hints in the logs?

**Comment by myhro** [comment]
Ha, got it:

    [1915.47107697] INFO: Creating a loopback volume
    [1916.03899002] DEBUG: Executing: truncate create --size=1024M /target/81cd2a46/volume.raw
    [2021.76308632] INFO: Attaching the volume
    [2022.48501778] DEBUG: Executing: losetup --show --find /target/81cd2a46/volume.raw
    [2027.84109116] DEBUG: /dev/loop0

This was introduced on 3ff1c57, when `truncate` replaced `qemu-img` for raw volumes. It doesn't expects the parameter `create`, so it creates a file with that name instead.

**Comment by andsens** [comment]
D'oh! Thank you @myhro :-)
