### ISSUE TITLE
Can't boot a jessie image

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#213]
[First spotted][jb-comment] by @jbergler on #165, looks like the problem regarding booting a `jessie` image isn't affecting only Vagrant/VirtualBox. Trying to boot a GCE instance (default manifest, changing only the `release`) results into this:

    Gave up waiting for root device.  Common problems:
     - Boot args (cat /proc/cmdline)
       - Check rootdelay= (did the syste[   34.801667] ACPI: bus type USB registered
    m wait long enough?)
       - Check root= (did the system wait for the right device?)
     - Missing modules (cat /proc/modules; ls /dev)
    ALERT!  /de[   34.809335] usbcore: registered new interface driver usbfs
    v/mapper/loop0p1 does not exist.  Dropping to a [   34.812606] usbcore: registered new interface driver hub
    shell!
    [   34.815440] usbcore: registered new device driver usb
    [   34.817879] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
    [   34.820937] ehci-pci: EHCI PCI platform driver
    modprobe: module ehci-orion not found in modules.dep
    [   34.827247] uhci_hcd: USB Universal Host Controller Interface driver
    [   34.830240] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
    [   34.833338] hidraw: raw HID events driver (C) Jiri Kosina
    [   34.835264] usbcore: registered new interface driver usbhid
    [   34.837089] usbhid: USB HID core driver

    BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) built-in shell (ash)
    Enter 'help' for a list of built-in commands.

    /bin/sh: can't access tty; job control turned off

Our first guess is that this is device mappers' fault, leaving `/dev/mapper/nbd0p2` or `/dev/mapper/loop0p1` as the root partition, when it should be identified by its UUID.

[jb-comment]: https://github.com/andsens/bootstrap-vz/pull/165#issuecomment-65066089

**Comment by andsens** [comment]
Which bootloader? If it's grub I am almost certain what the problem is. i.e. the fix I reverted yesterday.

**Comment by myhro** [comment]
Yes, it's grub. I'm a little bit confused, as the yesterday's revert was done because there wasn't a need for creating by hand those UUID links - not the opposite.

**Comment by andsens** [comment]
Except in this case that is exactly what it seems like. If the UUID symlinks aren't there, grub reverts to using the old dev paths. Can you extract grub.cfg from the image?

If you try re-reverting (:-D) the commit, does that fix it?

**Comment by myhro** [comment]
> If you try re-reverting (:-D) the commit, does that fix it?

Haha. This funny, as it [looks like that worked][boot-log], but I couldn't connect to the instance via SSH.

> Can you extract grub.cfg from the image?

Yes I can. Here's [the old one, that causes this bug][old-grub-cfg], and the [new one, from the image that's working][new-grub-cfg]. It's easy to see the difference on line 97.

Regarding #197, it seems that the `ed25519` key was properly generated:

`Apr 13 19:08:43 myhro-bvz-test regenerate-host-keys: Regenerating sshd key /etc/ssh/ssh_host_ed25519_key`

[boot-log]: https://gist.github.com/anonymous/44088666920a5c916fe0
[new-grub-cfg]: https://gist.github.com/anonymous/275b7a5f6e5b77773c91
[old-grub-cfg]: https://gist.github.com/anonymous/1d09f51b27c93b3c20aa

**Comment by myhro** [comment]
Anders,

I've "re-reverted" your patch in 22760c7, also adding a simple verification so we don't experience #210 again.

Ps.: I'm not sure if I should close this (as we did on #210) or mark it as `fixed in dev` (as usual). I'll leave it up to you. :-)

**Comment by andsens** [comment]
Hmpf, this annoys the hell out of me. I can't tell what the difference between non-working and working is. kpartx is the same version, but on some installs it creates the uuid link while on others it does not - 
maybe, just maybe, this has to do with some dpkg update scripts that screw things over.

If that is the case, new installs should work just fine, while old installs (but upgraded) should fail.
