### ISSUE TITLE
There were 2 instead of 1 matches for the expression `PermitRootLogin .*' in the file `/target/2a279fd4/root/etc/ssh/sshd_config'

### ISSUE THREAD

**Issue by aderumier** [andsens/bootstrap-vz#218]
Hi,
since this commit
https://github.com/andsens/bootstrap-vz/commit/2d3a0a0ce35e17dc183cf353ace2aed84f20accc

setting ssh root password not working anymore,

There were 2 instead of 1 matches for the expression `PermitRootLogin .*' in the file `/target/2a279fd4/root/etc/ssh/sshd_config'

because
/etc/ssh/sshd_config

have 2 lines with PermitRootLogin (one of them is a comment)

# cat sshd_config |grep PermitRootLogin

PermitRootLogin yes
# the setting of "PermitRootLogin yes

The problem is that
sed_i(sshd_config_path, '^PermitRootLogin .*', 'PermitRootLogin yes')
has been replaced by
sed_i(sshdconfig_path, 'PermitRootLogin .*', 'PermitRootLogin yes')

(missing ^)

**Comment by aderumier** [comment]
(this is with jesse)

**Comment by andsens** [comment]
Thanks for the bug report. I'll fix it tomorrow if I have the time.
... or you can send a PR :-) Just remember that it still has to work for wheezy and squeeze.

**Comment by myhro** [comment]
Closed by #219.
