### ISSUE TITLE
condition to enable EC2 init scripts?

### ISSUE THREAD

**Issue by jwendell** [andsens/bootstrap-vz#226]
Hi.

In our use case we don't want ec2 init scripts in our image. Currently they are always installed.
I'm wondering what is the best option to address our requirements:
- Add a manifest variable which controls whether they are installed or not;
- Write a [minimalist] plugin just to remove this task.

**Comment by andsens** [comment]
I'd definitely go for the manifest variable which is checked and excludes the corresponding tasks, anything else just adds more code.

**Comment by jwendell** [comment]
hmm, that's my opinion too. In which section would it fit better? provider?
Em 13/06/2015 14:35, "Anders Ingemann" <notifications@github.com> escreveu:

**Comment by andsens** [comment]
Yes. It's only applicable to ec2 after all.

**Comment by andsens** [comment]
Call it `install_init_scripts` and make it default to `true`.

**Comment by jwendell** [comment]
Change commited
