### ISSUE TITLE
EC2: Fixed volume size?

### ISSUE THREAD

**Issue by jwendell** [andsens/bootstrap-vz#237]
In the manifest file, I'm using a volume with 8G of size.
When I create an instance using the generated AMI, no matter the size of the storage I choose, the filesystem always will end up with 8G.

Is this the expected behavior?
In my opinion the volume should expand to fit the entire storage size...

Even the Debian official images "suffer" from this issue.

**Comment by andsens** [comment]
Could you post the manifest and log as gists? Normally the root partition should be autoexpanded.

**Comment by jwendell** [comment]
I think I found the issue:

cloud-init does that. Comparing to an ubuntu instance, I saw the cloud.cfg file is missing "growpart" in "cloud_init_modules" section.
In debian, the binary growpart is provided by cloud-utils package (which is not installed by default). I think it's a bit outdated, once cloud-init growpart module tries to access an invalid function of it: "growpart --update".

I'm trying to workaround this, but feel free to come with a solution :)

**Comment by jwendell** [comment]
Ok, I copied ubuntu's growpart script to the debian box and it worked. So, to fix this, I guess we should:

1) Update cloud-utils package in Jessie
2) Install cloud-utils package in AddEC2InitScripts.run() (or, in step 1, make it a dependency of cloud-init)
3) Add the line "- growpart" right before "resizefs" in /etc/cloud/cloud.cfg (this might be done along with step 1)

**Comment by flowhamster** [comment]
@jwendell ran into this while upgrading from wheezy to jessie AMI's using salt-cloud to provision. I'll spend some time later today to see if this will correct our issue.

**Comment by myhro** [comment]
Closing, as this should have been closed when #269 was merged.
