### ISSUE TITLE
Admin user plugin support for non-EC2 virtual machines

### ISSUE THREAD

**Issue by srivasta** [andsens/bootstrap-vz#248]
Hi,

 I like the admin_user plugin; and the facility it has to provide support for passwordless sudo by the admin user. For EC2 users, it also pulls in the EC2 credentials from the build machine into the image, allowing remote ssh access.

Unfortunately, there is little to allow for remote access in a GCE or a KVM machine created by biitstrap-vz, unless I am missing the process. We already have ar root password plugin; we can easily allow for an optional password to be provided for the ADMIN user; or perhaps an ssh authorize public key that can be dropped into the home directory of the newly created user. The default behaviour can remain unchanged.

I would be happy to send in a pull request, if this approach is acceptable.

  manoj

**Comment by andsens** [comment]
Do GCE or Azure have mechanisms to inject public keys? If so, i think we should go that route for those providers, for things like vbox and kvm adding a static pubkey should suffice.

When going the password route, password login should be re-enabled (off by default in jessie).
I think the pwd and pubkey options should be mutually exclusive.

> I would be happy to send in a pull request, if this approach is acceptable.

It would be welcome with open hands :-)
But I think we need to hash out the details first. Maybe some config examples?

**Comment by srivasta** [comment]
So a poor man’s option for what I am currently using with kvm has been:

plugins:
  admin_user:
    username: srivasta
  file_copy:
    mkdirs:
      - dir: /home/srivasta/.ssh
    files:
      - src: /home/srivasta/.ssh/id_rsa.pub
        dst: /home/srivasta/.ssh/authorized_keys
    commands:
      - [chown, ’-R’, ’srivasta:srivasta', {root}/home/srivasta/.ssh']
      - [chmod, ’0700', {root}/home/srivasta/.ssh']
      - [chmod, ’0600', {root}/home/srivasta/.ssh/authorized_keys']

Also, there is a suggested way to turn on password auth for ssh for the non-pubkey case:
    commands:
       - ['perl', '-pli.orig', -e''s/^\#\s*PasswordAuthentication\s+[Nn][Oo]/PasswordAuthentication Yes/msx', '/etc/ssh/sshd_config'

Ideally, I would like to see it internalized as either:
plugins:
  admin_user:
    username: srivasta
     password: test

Or:
  admin_user:
    username: srivasta
     pubkey: /home/srivasta/.ssh/id_rsa.pub

**Comment by andsens** [comment]
You suggestions look great. Go for it :-)
How should we go about static pubkeys on ec2. I'd say we disallow it or maybe log a warning message saying "You're using a static public key for the admin account. This will conflict with the ec2 public key injection mechanisn. The ec2-get-credentials startup script has therefore been disabled."

**Comment by srivasta** [comment]
Update: This is now code complete; running tests for the added functionality.

**Comment by srivasta** [comment]
Pull request:
https://github.com/andsens/bootstrap-vz/pull/252
