### ISSUE TITLE
fails to authenticate when using IAM role 

### ISSUE THREAD

**Issue by stumyp** [andsens/bootstrap-vz#259]
Hi, 
I have issues running bootstrap-vz with manifest with no Access keys in it.
So provider section looks like:
```
provider:
  name: ec2
  virtualization: hvm
  enhanced_networking: simple
```
the error is (I enabled debug logging for boto, to get more info)

```
Getting AWS credentials
Retrieving credentials from metadata server.
Retrieved credentials will expire in 6:30:07.213365 at: 2015-11-13T04:14:23Z
Connecting to EC2
Using access key provided by client.
Using secret key provided by client.
Determining the AMI name
Method: POST
Path: /
Data:
Headers: {}
Host: ec2.us-east-1.amazonaws.com
Port: 443
Params: {'Action': 'DescribeImages', 'Version': '2014-05-01', 'Owner.1': 'self'}
establishing HTTPS connection: host=ec2.us-east-1.amazonaws.com, kwargs={'port': 443, 'timeout': 70}
Token: None
using _calc_signature_2
query string: AWSAccessKeyId=XXXXXXXXXXXXXX&Action=DescribeImages&Owner.1=self&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2015-11-12T21%3A44%3A15Z&Version=2014-05-01
string_to_sign: POST
ec2.us-east-1.amazonaws.com
```

In the same time DescribeImages call made with cli tool:
`aws --debug --region=us-east-1  ec2 describe-images --owners self`

returns in particular: 
```
POST
ec2.us-east-1.amazonaws.com
/
AWSAccessKeyId=XXXXXXXXXXXXXX&Action=DescribeImages&Owner.1=self&SecurityToken=XXXLONG_SECURITY_TOKENXXX&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2015-11-12T21%3A42%3A17Z&Version=2014-06-15
```

It seems to me that bootstrap-vz does not use SecurityToken in the request.

I am trying with both github version and 0.9.9 from Debian unstable.

**Comment by stumyp** [comment]
`It seems to me that bootstrap-vz does not use SecurityToken in the request.` 
Correction: it looks like there is no use of instance profile and temporary credentials.

**Comment by andsens** [comment]
Sorry for the late answer. Do you have any suggestions on how to fix this? euca should of course get some extra options passed. I think with boto we just need to omit the credentials, it'll get the iam profile automatically...

**Comment by stumyp** [comment]
Unfortunately I'm not python expert, but from what I know about AWS auth
here how I work with MFA authentication in bash:
```
aws  --profile ${profile} sts get-session-token --serial-number ${serial}  --token-code ${token} >$TMP
export AWS_ACCESS_KEY_ID=`jq '.Credentials.AccessKeyId' <$TMP| sed -e 's/"//g'`
export AWS_SECRET_ACCESS_KEY=`jq '.Credentials.SecretAccessKey' <$TMP| sed -e 's/"//g'`
export AWS_SECURITY_TOKEN=`jq '.Credentials.SessionToken' <$TMP| sed -e 's/"//g'`
rm -f $TMP
```

in case of IAM role, it should be similar call, but instead of `get-session-token` it got to be `assume-role`. Let me try to do it on IAM enabled machine.

**Comment by stumyp** [comment]
sorry, stuck with something else. If you take a look at the output above, there are lines about `bootstrap-vz` getting auth credentials from metadata:
```
Getting AWS credentials
Retrieving credentials from metadata server.
Retrieved credentials will expire in 6:30:07.213365 at: 2015-11-13T04:14:23Z
```
So I guess credentials are received and can be used :smile:. That simplifies the task.

You can see these credentials by querying metadata server with curl:

```
# curl 169.254.169.254/2014-11-05/meta-data/iam/security-credentials/name_of_the_role_assigned
{
  "Code" : "Success",
  "LastUpdated" : "2015-12-09T15:48:09Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIXXXXXXXXXXX",
  "SecretAccessKey" : "XXXXXXXXXXXXXXXXX",
  "Token" : "_VERY_LONG_TOKEN_STRING_XXXXXXX",
  "Expiration" : "2015-12-09T22:02:58Z"
}
```

**Comment by stumyp** [comment]
Here is the link how it is done in PHP: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#instance-profile-credentials

More links and explanations here: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html
