### ISSUE TITLE
Connection timeout to undocumented IP

### ISSUE THREAD

**Issue by paul-gitseed** [andsens/bootstrap-vz#264]
https://github.com/andsens/bootstrap-vz/blob/master/bootstrapvz/providers/ec2/tasks/host.py#L26

When trying to retrieve the url mentioned in that line I get a connection timeout, this is stopping me from building ec2 images.

What the heck is this IP address anyway? This type of remote call seems insecure, especially since it is taking place over http (rather than https).

**Comment by myhro** [comment]
> What the heck is this IP address anyway?

This is a [reserved, non-routed, address][1] used to [fetch instance metadata][2] inside AWS network.

>  This type of remote call seems insecure, especially since it is taking place over http (rather than https).

I'm not sure if this is insecure indeed, as it is done inside their network.

[1]: https://tools.ietf.org/html/rfc3927
[2]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval

**Comment by paul-gitseed** [comment]
So that means you can only build ec2 instances from inside an ec2 instance?

**Comment by myhro** [comment]
> So that means you can only build ec2 instances from inside an ec2 instance?

Yes, you are right. Quoting the [EC2 provider documentation][1]:

> ... EBS volume backing only works on an EC2 host while S3 backed volumes should work locally (at this time however they do not, a fix is in the works).

Can we close this issue? :-)

[1]: https://bootstrap-vz.readthedocs.org/en/master/providers/ec2.html
