### ISSUE TITLE
Make a list of "known working builds"

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#266]
[As suggested][1] on #265, it would be nice if we make a list of what combination of architectures/providers/releases we know that are working, specially because this could indicate if there's someone supporting this configuration. 

Right now I can think of:

Release | Provider | Architecture | Person
------- | -------- | ------------ | ------
Jessie | EC2 | `amd64` | James Bromberger
Jessie | GCE | `amd64` | Zach Marano (and GCE Team)
Jessie | KVM | `arm64` | Clark Laughlin
Jessie | Oracle | `amd64` | Tiago Ilieve

Any other combination that we could add to the list? :-)

[1]: https://github.com/andsens/bootstrap-vz/pull/265#issuecomment-170075612

**Comment by srivasta** [comment]
Until the locales regression, I had KVM Sid/AMD64 working.

**Comment by myhro** [comment]
Manoj,

The problem with stating this about `sid/unstable` is that is somewhat hard to make sure if there's a regression with boostrap-vz or with this Debian release itself. I like this idea for `testing`, specially when it freezes, so we can take care of supporting the next release even before it's finished.

**Comment by andsens** [comment]
In any case, we should put the extra information on [this page](https://github.com/andsens/bootstrap-vz/blob/26d09d37768f256d16e70aaa04435b24473c1baa/docs/supported_builds.rst).

**Comment by myhro** [comment]
Anders,

I've updated the "supported builds" page, removing the mentions to `squeeze` and [opened an issue][1] so we can deal with this in the project as a whole.

[1]: https://github.com/andsens/bootstrap-vz/issues/280

**Comment by andsens** [comment]
Nice! Thank you Tiago!
