### ISSUE TITLE
Debian 8 AMI only using 8GB partition

### ISSUE THREAD

**Issue by shrimpwagon** [andsens/bootstrap-vz#267]
Every Debian 8 Jessie AMI that I launch in Amazon Web Services is only putting the root OS onto an 8GB partition regardless of what I set the size to at launch time. I know there is some documentation around how the size is set when an AMI is created. But I spoke to support at AWS and they said that this is unexpected behavior. Also, when I launch another Linux distro (eg Ubuntu) the same way I can set the root partition size at launch time no problem. I then begin to wonder why nobody has mentioned this much on the internet. I've searched around and haven't come up with any real answers. I'm also beginning to wonder if Debian is falling out, if I should go with Ubuntu. I still read on the internet that Debian is #1 choice for production web servers. I've also posted on forums and emailed Debian but I have yet to have a solid response about their EC2 AMIs.

All Debian 8 (Jessie) AMIs in community and marketplace I've tested with I could find all do the same thing. I've tried to launch with different EC2 tiers and they are all the same result. I've tried magnetic and SSD. Here's my post about it on serverfault: http://serverfault.com/questions/748063/debian-8-ami-only-using-8gb-partition. I'm launching in us-east-1*. This has been happening for a while actually. I've tried using Debian 8 AMIs from earlier in 2015 and they all doing the same thing. I can get you the AWS support transcript if you like but I would prefer if you can please just take my word for it. I'm just surprised that I have not found anything on the internet about this issue and that it hasn't been addressed yet. It's not just my account either. I've tried launching using totally different AWS accounts. Something is way jacked up

https://linuxacademy.com/blog/linux/resizing-root-partition-on-linux-in-amazon-ec2/
These instructions should work but look:

admin@ip-172-30-0-153:~$ lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda 202:0 0 40G 0 disk 
├─xvda1 202:1 0 1007.5K 0 part 
└─xvda2 202:2 0 8G 0 part /

admin@ip-172-30-0-153:~$ sudo resize2fs /dev/xvda2
sudo: unable to resolve host ip-172-30-0-153
resize2fs 1.42.12 (29-Aug-2014)
The filesystem is already 2096891 (4k) blocks long. Nothing to do!

admin@ip-172-30-0-153:~$ df
Filesystem 1K-blocks Used Available Use% Mounted on
/dev/xvda2 8124836 850000 6839076 12% /
udev 10240 0 10240 0% /dev
tmpfs 204596 4292 200304 3% /run
tmpfs 511484 0 511484 0% /dev/shm
tmpfs 5120 0 5120 0% /run/lock
tmpfs 511484 0 511484 0% /sys/fs/cgroup

The reason it says that it is already at 20GB is because I had originally set the volume to 20GB during launch. Then I created a snapshot and created this new volume and set to 40GB. Look how jacked up it is!

**Comment by andsens** [comment]
> Every Debian 8 Jessie AMI that I launch in Amazon Web Services is only putting the root OS onto an 8GB partition regardless of what I set the size to at launch time.

Paging @JamesBromberger, any idea what's going on here?

> These instructions should work but look

You are running resize2fs before you have resized the partition... 
run `sudo parted /dev/xvda resizepart 2 20G` first, then resize2fs will actually find free blocks to allocated :-)
(doublecheck that command, it's from the top of my head)

> The reason it says that it is already at 20GB is because I had originally set the volume to 20GB during launch.

Hm. Originally, before the official images used cloud-init, my growfs init script resized the FS on first boot and then disabled itself, to avoid running unnecessarily or doing something the admin did not intend. I *think* that *maybe* cloud-init *might* do something similar, but I'm out of my depth here since I don't use cloud-init, again I will have to defer to @JamesBromberger.

**Comment by myhro** [comment]
> Paging @JamesBromberger, any idea what's going on here?

I've talked with James in private (my bad for not asking him on the `debian-cloud` mailing list). This is a known ([#784004][1]) bug. Essentially, what happened is that the `growpart` command doesn't work as expected on `jessie`.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784004

**Comment by shrimpwagon** [comment]
Please help. Trying. Maybe I'm not doing something right?

    root@ip-172-30-0-243:/home/admin# fdisk -l
    
    Disk /dev/xvda: 20 GiB, 21474836480 bytes, 41943040 sectors
    Units: sectors of 1 * 512 = 512 bytes
    Sector size (logical/physical): 512 bytes / 512 bytes
    I/O size (minimum/optimal): 512 bytes / 512 bytes
    Disklabel type: gpt
    Disk identifier: 982CE179-5AB5-4BAB-AFAB-844E8F5FCA45
    
    Device     Start      End  Sectors    Size Type
    /dev/xvda1    34     2048     2015 1007.5K BIOS boot
    /dev/xvda2  2049 16777182 16775134      8G Linux filesystem
    
    root@ip-172-30-0-243:/home/admin# parted /dev/xvda resizepart 2 20G
    Warning: Partition /dev/xvda2 is being used. Are you sure you want to continue?
    parted: invalid token: 20G                                                
    Yes/No? yes                                                               
    End?  [8590MB]?                                                           
    Information: You may need to update /etc/fstab.
    
    root@ip-172-30-0-243:/home/admin# resize2fs /dev/xvda2                    
    resize2fs 1.42.12 (29-Aug-2014)
    The filesystem is already 2096891 (4k) blocks long.  Nothing to do!
    
    root@ip-172-30-0-243:/home/admin# df
    Filesystem     1K-blocks   Used Available Use% Mounted on
    /dev/xvda2       8124836 850712   6838364  12% /
    udev               10240      0     10240   0% /dev
    tmpfs             204596   4292    200304   3% /run
    tmpfs             511484      0    511484   0% /dev/shm
    tmpfs               5120      0      5120   0% /run/lock
    tmpfs             511484      0    511484   0% /sys/fs/cgroup

**Comment by andsens** [comment]
You're using `fdisk`. I don't think `fdisk` works as expected with `gpt`, use parted. @shrimpwagon, closing this issue, since it is not a problem with bootstrap-vz.

**Comment by shrimpwagon** [comment]
Thank you for the great responses. Thank you @andsens for pointing me in the right direction with resizing the partition. It was close but here is the way to do it:

    root@ip-172-30-0-243:/home/admin# parted /dev/xvda resizepart 2
    Warning: Partition /dev/xvda2 is being used. Are you sure you want to continue?
    Yes/No? Yes                                                               
    End?  [8590MB]? End                                                       
    Error: Invalid number.
    root@ip-172-30-0-243:/home/admin# parted /dev/xvda resizepart 2           
    Warning: Partition /dev/xvda2 is being used. Are you sure you want to continue?
    Yes/No? Yes                                                               
    End?  [8590MB]? 20GB                                                      
    Information: You may need to update /etc/fstab.

    root@ip-172-30-0-243:/home/admin# resize2fs /dev/xvda2 
    resize2fs 1.42.12 (29-Aug-2014)
    Filesystem at /dev/xvda2 is mounted on /; on-line resizing required
    old_desc_blocks = 1, new_desc_blocks = 2
    The filesystem on /dev/xvda2 is now 4882556 (4k) blocks long.
    
    root@ip-172-30-0-243:/home/admin# df
    Filesystem     1K-blocks   Used Available Use% Mounted on
    /dev/xvda2      19090620 854756  17354452   5% /
    udev               10240      0     10240   0% /dev
    tmpfs             204596   4292    200304   3% /run
    tmpfs             511484      0    511484   0% /dev/shm
    tmpfs               5120      0      5120   0% /run/lock
    tmpfs             511484      0    511484   0% /sys/fs/cgroup

For the `parted` command you don't need the last parameter. The command will ask you the ending block size and you just pop in the size of the disk.

**Comment by JamesBromberger** [comment]
(Hasily recalling) It is an issue with newer growpart on Debian - newer
than what cloud-init used to use. The command line arguments changed in
growpart, so that cloud-init that Debian packaged was not compatible
with the version of growpart in cloud-utils. This is fixed in newer
cloud-init, but unfortunately despite many requests, we don't have an
updated Debian package of Cloud-init yet in backports or unstable that
we can cherry-pick from.

As you saw, it is possible to manually resize the partition, but its far
from user friendly (as it should be).


On 11/01/2016 11:05 AM, Shawn Welch wrote:
>
> Please help. Trying. Maybe I'm not doing something right?
>
> |root@ip-172-30-0-243:/home/admin# fdisk -l Disk /dev/xvda: 20 GiB,
> 21474836480 bytes, 41943040 sectors Units: sectors of 1 * 512 = 512
> bytes Sector size (logical/physical): 512 bytes / 512 bytes I/O size
> (minimum/optimal): 512 bytes / 512 bytes Disklabel type: gpt Disk
> identifier: 982CE179-5AB5-4BAB-AFAB-844E8F5FCA45 Device Start End
> Sectors Size Type /dev/xvda1 34 2048 2015 1007.5K BIOS boot /dev/xvda2
> 2049 16777182 16775134 8G Linux filesystem
> root@ip-172-30-0-243:/home/admin# parted /dev/xvda resizepart 2 20G
> Warning: Partition /dev/xvda2 is being used. Are you sure you want to
> continue? parted: invalid token: 20G Yes/No? yes End? [8590MB]?
> Information: You may need to update /etc/fstab.
> root@ip-172-30-0-243:/home/admin# resize2fs /dev/xvda2 resize2fs
> 1.42.12 (29-Aug-2014) The filesystem is already 2096891 (4k) blocks
> long. Nothing to do! root@ip-172-30-0-243:/home/admin# df Filesystem
> 1K-blocks Used Available Use% Mounted on /dev/xvda2 8124836 850712
> 6838364 12% / udev 10240 0 10240 0% /dev tmpfs 204596 4292 200304 3%
> /run tmpfs 511484 0 511484 0% /dev/shm tmpfs 5120 0 5120 0% /run/lock
> tmpfs 511484 0 511484 0% /sys/fs/cgroup |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andsens/bootstrap-vz/issues/267#issuecomment-170421790>.
>


-- 
/Mobile:/ +61 422 166 708, /Email:/ james_AT_rcpt.to

**Comment by shrimpwagon** [comment]
Sent to Debian lists:
https://lists.debian.org/debian-cloud/2016/01/msg00035.html

**Comment by jwendell** [comment]
I don't have the time to work on it anymore, but there's a working fix around for a while: https://github.com/andsens/bootstrap-vz/pull/239

**Comment by shrimpwagon** [comment]
Sorry, not sure how to implement the fix. Thank you.

**Comment by john-pierce** [comment]
I build our private AMIs without partitioning and just use the raw EBS volume without encountering this problem. Could simply not supporting partitioned volumes on AWS EBS be an interim solution?
