### ISSUE TITLE
bootstrap-vz does not work with euca2ools 3xx

### ISSUE THREAD

**Issue by eugenea** [andsens/bootstrap-vz#27]
Different command switches needed.

As for euca2ools2x it conflicts with boto library higher than 0.21 version. Finding proper boto version is challenging.

**Comment by jszwedko** [comment]
@eugenea it looks like 2.0 has the flags that bootstrap-vz expects.

**Comment by jszwedko** [comment]
However it appears that that version points to an old API endpoint is it fails anyway.

**Comment by jszwedko** [comment]
I'm getting the `InvalidManifest` errors now too.

**Comment by andsens** [comment]
Try using the `wip-integration-testing` branch. I've started testing S3 instances and initial results seem to be promising, though I haven't gone through all the combinations yet. You could even try using S3 backing for HVM instances (but you'll need to remove [this guard](https://github.com/andsens/bootstrap-vz/blob/b7579920a35aae076908c37dc3505aa5459bba0b/bootstrapvz/providers/ec2/__init__.py#L51)).

**Comment by andsens** [comment]
Oh, and make sure to install the right version of euca2ools [as per the docs](https://github.com/andsens/bootstrap-vz/wiki/dev_Home/54142bfaa18d30dffeb67770577b4441af508b0a#amazon-ec2-ebs-backed-ami).
