### ISSUE TITLE
Update Documentation, Packages / Sources

### ISSUE THREAD

**Issue by apolloclark** [andsens/bootstrap-vz#272]
The documentation is incorrect for Packages / Sources:

It should be:
      sources:
        puppet:
          - deb http://apt.puppetlabs.com wheezy main dependencies

If you use the default, it throws a type error within the yaml schema validator.

**Comment by myhro** [comment]
Hi Apollo,

You're right. The [description states][1] that it should be a map/dictionary, but the example was showing a list. I've fixed it.

Thanks for spotting (and reporting) that. 

Regards,
Tiago.

[1]: http://bootstrap-vz.readthedocs.org/en/master/manifests/index.html#packages
