### ISSUE TITLE
Cannot run AWS Provider Locally

### ISSUE THREAD

**Issue by apolloclark** [andsens/bootstrap-vz#273]
I can't run the AWS provider from my localhost

```Shell
$ sudo bootstrap-vz/bootstrap-vz bootstrap-vz/manifests/official/ec2/ebs-jessie-amd64-hvm.yml
Adding openssh package
Adding commands required for formatting
Adding locale package to bootstrap installation
Creating workspace
Getting AWS credentials
Silence boto debug logging
Adding commands required for bootstrapping Debian
Retrieving instance metadata
<urlopen error [Errno 113] No route to host>
Traceback (most recent call last):
  File "/home/apollo/Sites/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/home/apollo/Sites/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/home/apollo/Sites/bootstrap-vz/bootstrapvz/providers/ec2/tasks/host.py", line 27, in run
    response = urllib2.urlopen(url=metadata_url, timeout=600)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 113] No route to host>
Rolling back
```

Local system:
Ubuntu 15.10
aws-cli/1.9.17 Python/2.7.10 Linux/4.4.0-rc6-custom botocore/1.3.17

I use aws-cli locally all the time. I noticed in hosts.py, it's calling to the local AWS meta-data provider at "http://169.254.169.254/latest/dynamic/instance-identity/document", which would fail if called from a local shell instance. Is it required to run this from within an existing AWS instance? If so, wouldn't that just use that individual instances meta-data, and not the meta-data of the newly created instance?

**Comment by myhro** [comment]
Apollo,

This is a known issue, discussed in #264 a few weeks ago. Currently, it is not possible to bootstrap EC2 images outside AWS. :-(

I'm not really sure what is needed to do this right now. Can you shine a light here, @andsens ?

**Comment by apolloclark** [comment]
Ok, thanks for the info. I'll look into this. I suspect a lot of the info here can be passed manually through the yml config file.

**Comment by apolloclark** [comment]
Ok, I got this working on AWS, using another Debian Jessie instance. Here are the steps, for anyone interested:

```Shell
sudo apt-get update
sudo apt-get install -y -q kpartx nbd-client qemu-utils debootstrap python-pip git
sudo pip install termcolor jsonschema fysom docopt pyyaml boto
git clone https://github.com/andsens/bootstrap-vz.git
# update eb-jessie-amd64-hvm.yml, with AWS credentials

sudo modprobe nbd
sudo bootstrap-vz/bootstrap-vz bootstrap-vz/manifests/official/ec2/ebs-jessie-amd64-hvm.yml
```

**Comment by myhro** [comment]
Thanks, Apollo. This is almost [what is currently documented][1], except for the packages needed for partitioning (like `nbd-client` and `qemu-utils`), which aren't used by the official manifest AFAIK.

Can we close this issue?

P.s.: @andsens can you please open an issue detailing what needs to be done so we can be able to bootstrap S3-backed instances locally, so we can track this in a proper place?

[1]: https://github.com/andsens/bootstrap-vz/blob/72699d09c8d18fccb6f434023f33c92ca4ad94ca/README.rst#amazon-ec2-ebs-backed-ami

**Comment by andsens** [comment]
Hi @myhro. @apolloclark is getting that error because he is trying to bootstrap an EBS instance outside AWS. [Check this out](https://github.com/andsens/bootstrap-vz/blob/c130368603d4f323ae819dc7b6e830892a463870/bootstrapvz/providers/ec2/__init__.py#L94), the task that fails is only added when bootstrapping EBS instances. bootstrap-vz should be able to bootstrap S3 backed instances outside of AWS just fine.

I really should get around to fixing #189, then we could avoid a lot of confusion.

**Comment by myhro** [comment]
> I really should get around to fixing #189, then we could avoid a lot of confusion.

Sorry for asking you that. I totally forgot about this issue. :-)
