### ISSUE TITLE
Virtualbox Provider, cannot ssh login

### ISSUE THREAD

**Issue by apolloclark** [andsens/bootstrap-vz#274]
I build the default "examples/virtualbox/jessie-vagrant.yml", and cannot correctly "vagrant up". It fails on SSH login using the default insecure vagrant key. Does it require adding the "root_password" or "admin_user" plugin?

**Comment by myhro** [comment]
> Does it require adding the "root_password" or "admin_user" plugin?

No, [it doesn't][1]. I'll take a look to see what is happening.

[1]: https://github.com/andsens/bootstrap-vz/blob/72699d09c8d18fccb6f434023f33c92ca4ad94ca/bootstrapvz/plugins/vagrant/tasks.py#L49

**Comment by myhro** [comment]
Apollo,

I've bootstrapped the `jessie-vagrant.yml` manifest and could use `vagrant up` and `vagrant ssh` with no problem. The versions of VirtualBox and Vagrant used in this process were the defaults for `jessie`:

    [myhro@viridian:~]$ VBoxManage --version
    4.3.32_Debianr103443
    [myhro@viridian:~]$ vagrant --version
    Vagrant 1.6.5

You can [download the box][1] (485 MB) if you like.

[1]: http://viridian.ilieve.org/vagrant/debian-jessie-amd64-160126.box

**Comment by apolloclark** [comment]
Strange... I ran the build 3 times, each time failed, now it's working. I'm using the latest versions of virtualbox: 5.0.14r105127, and vagrant: 1.8.1, on Ubuntu 15.10. I'll open another ticket in a few days if I see it happen again, along with the vagrant debug output. Thanks!
