### ISSUE TITLE
Support for Stretch and Sid

### ISSUE THREAD

**Issue by apolloclark** [andsens/bootstrap-vz#275]
Has anyone done work on this? Basically, I'm looking to run Debian with the newer 4.3 kernel in Amazon and Azure.

**Comment by myhro** [comment]
Hi Apollo,

I'm not aware if anyone is working on `stretch`/`sid` support right now, but if you are looking for a 4.3 kernel, there's one on `jessie-backports`: https://packages.debian.org/jessie-backports/linux-image-amd64 (currently `4.3+70~bpo8+1`).

Regards,
Tiago.

**Comment by apolloclark** [comment]
Ok, so I tried getting stretch to build. The bootstrap-va build succeeded, but the actual Virtualbox VM is broken. Specifically, it can't initialize "eth0", and is listing it as "enp0s3". I'll push a pull request with my local changes.

**Comment by andsens** [comment]
Alright. This is actually #245 then. I'm closing this one, so we can keep the discussion in one place. Check the issue out, I think the comments would be a great help for implementing this.
