### ISSUE TITLE
Add support for Stretch, Amazon

### ISSUE THREAD

**Issue by apolloclark** [andsens/bootstrap-vz#277]
Now that I got Stretch working on Virtualbox, I'm going to work on getting it going on Amazon.

This isn't a ticket... it's a promise.

**Comment by andsens** [comment]
Haha, nice. I'll be merging your PR soon and get working on splitting up the different grub configs.

**Comment by apolloclark** [comment]
Should I create a new branch in my fork of the repo for this? I tried doing a build last night, wasn't able to SSH login, then hardcoded the root password with the root_password plugin, logged in. I noticed the "admin" user wasn't being set, so I'm wondering if the cloud_init plugin is failing somewhere. I'll post the debug script after another run today.

**Comment by andsens** [comment]
I'd say a new branch. I'll probably merge your changes into a separate branch as well before merging it into master.

**Comment by apolloclark** [comment]
Sounds like a plan. I created a new branch on my fork "amazon-support".

**Comment by vorlock** [comment]
AMI generation for Stretch is has been sorted in PR#344, so I think this issue can be closed
