### ISSUE TITLE
Fails while setting the timezone (Sid, testing)

### ISSUE THREAD

**Issue by srivasta** [andsens/bootstrap-vz#279]
Hi,

   Running a git clone of master, I am getting a recent error (I last updated Mid January, and thing s worked then)

   Manoj

[build.yml.txt](https://github.com/andsens/bootstrap-vz/files/120219/build.yml.txt)

Setting the selected timezone
`/usr/share/zoneinfo/UTC` and `/scratch/sandbox/build/f38e0342/root/etc/localtime` are the same file
Traceback (most recent call last):
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/common/tasks/locale.py", line 53, in run
    copy(zoneinfo_path, localtime_path)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/usr/share/zoneinfo/UTC` and `/scratch/sandbox/build/f38e0342/root/etc/localtime` are the same file
Rolling back
Unmounting the bootstrap volume
Removing volume partitions mapping
Detaching the volume
Deleting mountpoint for the bootstrap volume
Deleting the volume
Deleting workspace
Successfully completed rollback
Traceback (most recent call last):
  File "/usr/local/src/bootstrap-vz/bootstrap-vz", line 5, in <module>
    main()
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
    dry_run=opts['--dry-run'])
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/usr/local/src/bootstrap-vz/bootstrapvz/common/tasks/locale.py", line 53, in run
    copy(zoneinfo_path, localtime_path)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))

**Comment by srivasta** [comment]
On my Sid machine, /etc/localtime is a symlink:
0 lrwxrwxrwx 1 root root 39 Feb  5 17:15 /etc/localtime -> /usr/share/zoneinfo/America/Los_Angeles

So shutil.copy will raise an ERROR since the srec and dst are the same file.
Looking at the config maintainer scripot from tzdata, I see the logic is that if  /etc/localtime is a link, update /etc/timezone based on the target of the localtime link. (/etc/timezone is indeed a regular file).. Otherwise, if it exists, the /etc/timezone is the source of truth.

Perhaps we should set the /etc/localtime to be a link to UTC, and update /etc/timezone?

See: http://sources.debian.net/src/tzdata/2016a-1/debian/tzdata.config/?hl=391#L329

**Comment by srivasta** [comment]
Something like this will instantiate teh same behaviour as dpkg --reconfigure tzdata will. I can send a pull request.

Manoj

diff --git i/bootstrapvz/common/tasks/locale.py w/bootstrapvz/common/tasks/locale.py
index 06dbeb3..b96d2c9 100644
--- i/bootstrapvz/common/tasks/locale.py
+++ w/bootstrapvz/common/tasks/locale.py
@@ -50,4 +50,8 @@ class SetTimezone(Task):
                        tz_file.write(timezone)
                zoneinfo_path = os.path.join(info.root, '/usr/share/zoneinfo', timezone)
                localtime_path = os.path.join(info.root, 'etc/localtime')
-               copy(zoneinfo_path, localtime_path)
+               if os.path.islinnk(localtime_path):
+                       os.unlink(localtime_path)
+                       os.symlink(os.path.join('/usr/share/zoneinfo', timezone), localtime_path)
+               else:
+                       copy(zoneinfo_path, localtime_path)

**Comment by andsens** [comment]
While the patch looks reasonable, this
```
if os.path.islink(localtime_path):
```

... is a problem. We should *always* know the initial state of the system, so we'll have to figure out when this changed and make two separate tasks.

**Comment by srivasta** [comment]
```
tzdata (2016a-1) unstable; urgency=medium

  [ Aurelien Jarno ]
  * Add Vcs-Git and Vcs-Browser fields to debian/control.
  * New upstream version, affecting the following future time stamps:
    - America/Cayman
    - Asia/Chita
    - Asia Tehran
  * Change /etc/timezone into a symlink (closes: #803144)

 -- Aurelien Jarno <aurel32@debian.org>  Fri, 29 Jan 2016 17:26:32 +0100
```

**Comment by srivasta** [comment]
So create two different tasks, and decide in __init.py__? Could you help me understand why looking at whether or not /etc/localtime is a symlink and preserving the symlinkness at image creation time is a bad idea? I thought that doing this while building the image would be a backward compatible change.

**Comment by srivasta** [comment]
tzdata     | 2016a-1         | testing                    | source, all
tzdata     | 2016a-1         | unstable                   | source, all

**Comment by andsens** [comment]
> Could you help me understand why looking at whether or not /etc/localtime is a symlink and preserving the symlinkness at image creation time is a bad idea?

Because if we don't make it dependent on the distribution we will have no clue when we can delete the old code. This way we have a clause that says `if info.release > release.jessie:`, which means once we stop supporting jessie, we can delete that entire task. It is also in sync with the mantra of directing the control flow through the tasklist rather than inside each task.

**Comment by srivasta** [comment]
Thanks for the explanation. I'll take a crack at it unless someone gets there first

**Comment by srivasta** [comment]
Added pull request #281  to address this issue

**Comment by srivasta** [comment]
The pull request #281 has been merged, and tested on a Sid KVM image.
