### ISSUE TITLE
Allow debconf values to be specified

### ISSUE THREAD

**Issue by nbraud** [andsens/bootstrap-vz#282]
Currently, it seems impossible to specify `debconf(7)` values for preconfiguring packages.

Should there be interest (and I assume so, given that the ability to configure package is generaly useful), I can have a go at implementing this.

**Comment by andsens** [comment]
There's a fine line between configuration management and bootstrapping with preconfiguration ([as discussed previously](https://github.com/andsens/bootstrap-vz/pull/215#issuecomment-96842276)). Seeing how this is quite close to package installation itself though, I am inclined to say that it does fall within purview of bootstrap-vz. @myhro you got any opinion on this?

**Comment by nbraud** [comment]
@andsens That's a pretty good point.  It made sense to me partly because my mental model of the manifest is fairly similar to a preseed file (in function, not structure).
More generally, I believe that it makes sense to be able to control that part of package installation without going as far as requiring full-blown config management  :-)

Thanks a lot for the speedy answer.

**Comment by myhro** [comment]
> @myhro you got any opinion on this?

I'm not sure if I understood the issue properly. Is somewhat like [what we have][1] for the cloud-init plugin?

[1]: https://github.com/andsens/bootstrap-vz/blob/518efec1aa2a62ea65ff7dc075af47bb1e1e36a4/bootstrapvz/plugins/cloud_init/tasks.py#L60

**Comment by nbraud** [comment]
@myhro I'm not sure I understand what that line does (more specifically, what `sources` is), but it's indeed about running `debconf-set-selections` in the chroot before installing packages.

**Comment by myhro** [comment]
Nicolas,

> ... (more specifically, what `sources` is) ...

It is just a string, like you can see from [the previous lines][1]. E.g.: `Ec2` (with capital `e`) for the EC2 provider.

-

Anders,

I'm sitting in a wall here. In a way, it looks like something that is supposed to be done by an orchestration tool... But as you said, it is really close to package installation and we already do this on one specific case. So, I guess that the outcome is: yes, we should definitely add this to our TODO list. :-)

[1]: https://github.com/andsens/bootstrap-vz/blob/518efec1aa2a62ea65ff7dc075af47bb1e1e36a4/bootstrapvz/plugins/cloud_init/tasks.py#L52

**Comment by nbraud** [comment]
Just to avoid duplicating work, I have an implementation of that.
I just need to check a few more things (including whether I need authorization from `${WORK}` to contribute patches) and I will submit a PR.
