### ISSUE TITLE
Official Debian 8.3 AMI

### ISSUE THREAD

**Issue by codefx9** [andsens/bootstrap-vz#283]
Hi,
Are there any plans to release official Debian 8.3 AMIs? Are there any known issues just in case I try to build it myself?

Thanks.

**Comment by myhro** [comment]
Hello @codefx9,

Yes, there are plans but I can't give you an ETA. The maintainer for EC2 images is @JamesBromberger and he looks a lot busy lately.

The main issue we are dealing right now is the problem with `cloud-utils`/`growpart` (discussed in #237 and #267). There's a fix for this waiting in the [BACKPORTS-NEW queue][1].

May I ask you to close this issue, please? The proper place to discuss this is the [`debian-cloud` mailing list][2]. We maintain the tool to build it here, but the entire process of releasing a new image is discussed out there, as you can see at the announcements of [8.1][3] and [8.2 (pre-release)][4].

Regards,
Tiago.

[1]: https://ftp-master.debian.org/backports-new.html
[2]: https://lists.debian.org/debian-cloud/
[3]: https://lists.debian.org/debian-cloud/2015/06/msg00015.html
[4]: https://lists.debian.org/debian-cloud/2015/11/msg00004.html

**Comment by JamesBromberger** [comment]
On 14/02/2016 1:49 AM, Tiago Ilieve wrote:
>
> Hello @codefx9 <https://github.com/codefx9>,
>
> Yes, there are plans but I can't give you an ETA. The maintainer for
> EC2 images is @JamesBromberger <https://github.com/JamesBromberger>
> and he looks a lot busy lately.
>
> The main issue we are dealing right now is the problem with
> |cloud-utils|/|growpart| (discussed in #237
> <https://github.com/andsens/bootstrap-vz/issues/237> and #267
> <https://github.com/andsens/bootstrap-vz/issues/267>). There's a fix
> for this waiting in the BACKPORTS-NEW queue
> <https://ftp-master.debian.org/backports-new.html>.
>
> May I ask you to close this issue, please? The proper place to discuss
> this is the |debian-cloud| mailing list
> <https://lists.debian.org/debian-cloud/>. We maintain the tool to
> build it here, but the entire process of releasing a new image is
> discussed out there, as you can see at the announcements of 8.1
> <https://lists.debian.org/debian-cloud/2015/06/msg00015.html> and 8.2
> (pre-release)
> <https://lists.debian.org/debian-cloud/2015/11/msg00004.html>.
>
>

I will re-sync my tree and push an image tonight after the kids have
gone to bed! ;)  I did do this last weekend, and re-tested with
cloud-initramfs tools to grow, but that didn't work automatically
(various bashing the gpt table and rebooting again did work for root
resize).


-- 
/Mobile:/ +61 422 166 708, /Email:/ james_AT_rcpt.to

**Comment by myhro** [comment]
This is awesome, James! Thank you.

> I did do this last weekend, and re-tested with cloud-initramfs tools to grow, but that didn't work automatically (various bashing the gpt table and rebooting again did work for root resize).

So, looks like the fix provided by #269 doesn't work with GPT partitions, right? This is something that I was suspicious, because the support for it officially came with cloud-utils `0.27` (which is the backported and last released version).
