### ISSUE TITLE
Sourceforge failure causes AWS image building to fail

### ISSUE THREAD

**Issue by justinsb** [andsens/bootstrap-vz#287]
When building an AWS image with enhanced networking, a driver is downloaded from sourceforge.

SourceForge seems to continually be having problems, and this often causes bootstrap-vz builds to fail.

Is there some other place we could get the ixgbevf driver? :
https://github.com/andsens/bootstrap-vz/blob/0b9c8181feec6fb3c6818b0d75e29b100bd751bf/bootstrapvz/providers/ec2/tasks/network.py#L91

For example, as I file this bug, for that download sourceforge is returning:

```
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

**Comment by justinsb** [comment]
I did find what I believe to be the same download at https://downloadmirror.intel.com/25464/eng/ixgbevf-2.16.1.tar.gz, although I can't validate this while sourceforge is down.

That link also has the advantage of being an https link, so there's less need for a shasum...

**Comment by andsens** [comment]
I like downloading the driver from the original manufacturer with https a lot better. Can you send a PR with the changes? Maybe also split up the download and the compilation so that we can fail early (i.e. in the preparation phase), if the download fails.

**Comment by justinsb** [comment]
Yes - I'll send a PR!  I note that the JamesBromberger fork has currently bumped the version from 2.16.1 to 2.16.4, so I guess I do that (one of us will have a merge conflict, sadly, but hopefully it'll be me if I merge second)

**Comment by sarnowski** [comment]
```
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

Happened again :-( Unfortunately, switching to Intel's page doesn't work as well:

```
Installing enhanced networking kernel driver using DKMS
[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/root/bootstrap-vz/bootstrapvz/base/main.py", line 109, in run
    tasklist.run(info=bootstrap_info, dry_run=dry_run)
  File "/root/bootstrap-vz/bootstrapvz/base/tasklist.py", line 43, in run
    task.run(info)
  File "/root/bootstrap-vz/bootstrapvz/providers/ec2/tasks/network.py", line 96, in run
...
```

I assume that the CA certificates for Python are missing? But I am not Python guru. In general, it would be great to switch to Intel's official source as Sourceforge not only has bad reputation in the last years but also a very bad uptime.

**Comment by andsens** [comment]
Argh. @justinsb you never sent that PR :-)

**Comment by justinsb** [comment]
I didn't, sorry ... I will.

A user told me they hit the CERTIFICATE_VERIFY_FAILED when using a Debian 8.3 image as the builder, though it went away with the 8.1 image.  Technically they were using a 8.3 Debian image in the cn-north-1 region though it wasn't listed on the official page.  Not sure if this was specific to the cn-north-1 image or applies to all 8.3 images.

**Comment by dansteen** [comment]
Ok.  The problem is that this certificate: `https://gte-cybertrust-global-root.digicert.com/info/index.html` is no longer trusted by debian.  In fact, it's no longer trusted by my browser either, though it's still valid.   The page listed here:  `https://www.digicert.com/digicert-root-certificates.htm` (look for "GTE CyberTrust Global Root")  indicates that it's "deprecated by some browsers", probably because it's expiring soon.

The solution for me was to do the following:

```
curl https://www.digicert.com/CACerts/GTECyberTrustGlobalRoot.crt
openssl x509 -in GTECyberTrustGlobalRoot.crt -inform der > /usr/local/share/ca-certificates/GTE.crt
sudo /usr/local/update-ca-certificates
```

STUPID DISCLAIMER:  If you do the above, you are trusting a certificate that seems to have been deliberately dropped from debian.  You do this at your own risk blah blah blah.
