### ISSUE TITLE
Corrupt manifest for S3

### ISSUE THREAD

**Issue by eugenea** [andsens/bootstrap-vz#29]
<Response><Errors><Error><Code>InvalidManifest</Code><Message>Invalid AMI manifest</Message></Error>

Cant tell what is wrong with manifest, looks ok to me but amazont won't accept it.

**Comment by jszwedko** [comment]
The manifest appears to be valid when using version `3.2.0` (and master) of `euca2ools`.

**Comment by andsens** [comment]
Closing since it really is a duplicate of #27
