### ISSUE TITLE
expand-root init.d script is not assigning root_device_path correctly

### ISSUE THREAD

**Issue by zmarano** [andsens/bootstrap-vz#304]
With the changes to the common expand-root script, the device is filled in with info.volume.device_path which turns out to point to the device of the install volume. If you are using a raw volume for example this means you end up with /dev/loop0 as the resulting device that is supposed to be expanded. This is obviously wrong and should be whatever the boot drive actually is (normally /dev/sda but could be other things).

**Comment by eranmeir** [comment]
The actual device path can be a on a different volume, e.g.,
```
Creating a loopback volume
Executing: truncate --size=10240M /target/3bdaa011/volume.raw
Attaching the volume
Executing: losetup --show --find /target/3bdaa011/volume.raw
/dev/loop3
```

 expand-root would then give the following error: 

```
Adjusting the expand-root device
There were 0 instead of 1 matches for the expression `/dev/loop0' in the file `/target/3bdaa011/root/etc/init.d/expand-root'
```
