### ISSUE TITLE
Duplicated GCE manifest

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#310]
Hi @zmarano,

I was warned by lintian when building the boostrap-vz Debian package:

`X: bootstrap-vz: duplicate-files usr/share/doc/bootstrap-vz/examples/manifests/official/gce/jessie-backports.yml usr/share/doc/bootstrap-vz/examples/manifests/official/gce/jessie.yml`

Turns out that indeed, the manifests `jessie.yml` and `jessie-backports.yml` are the same:

    [myhro@leptok:~/bootstrap-vz]$ md5sum manifests/official/gce/*
    a909707cc6371dd0efc8292da5281bfc  manifests/official/gce/jessie-backports.yml
    a909707cc6371dd0efc8292da5281bfc  manifests/official/gce/jessie.yml
    1b6e9801e96d8386cfb446f2c8efa247  manifests/official/gce/README.rst
    a1f2a9c392a3e5f1ad4032c5b6274167  manifests/official/gce/wheezy-backports.yml
    4e94caae0dea98e81caa271695a8f260  manifests/official/gce/wheezy.yml

Looks like there isn't a version of Jessie with the backported kernel/SSH. Can we remove the `jessie-backports.yml` file? My concern is that it may being used internally (and possibly being treated as a version with backports, when actually it isn't).

Regards,
Tiago.

**Comment by zmarano** [comment]
Actually I have an upcoming PR that removes it but if you want to do it right now go for it. It was spurious. We never ended up using it and so it can be removed.

**Comment by myhro** [comment]
Thank you, Zach. I'm removing it then.
