### ISSUE TITLE
Question about volumes

### ISSUE THREAD

**Issue by xleliberty** [andsens/bootstrap-vz#351]
Hi, 
after reading the doc, i'me still asking me a question: ? 
it's not possible to create other partitions, only boot, root and swap ? 

i would like to have something like that

volume:
    root: 16GiB
    home: 32GiB
    var: 100GiB

is there a way to achieve this ? 

Thanks you very much

**Comment by andsens** [comment]
Unfortunately you cannot do that with the standard manifest. The abstractions are there but I haven't gotten around to creating a sensible manifest schema that would allow for this. However, you should be able to use said [abstractions](https://github.com/andsens/bootstrap-vz/blob/5250f8233215f6f2e3a571be2f5cf3e09accd4b6/bootstrapvz/base/fs/partitionmaps/gpt.py) if you [create a plugin](https://github.com/andsens/bootstrap-vz-example-plugin) for it. It would look something like this:

```python
p_map = info.volume.partition_map
sector_size = Bytes('512B')
partition_gap = Sectors(1, sector_size)  # The gap is added to make `parted' happy.
var_size = Sectors(Bytes('100GiB'), sector_size)
var = GPTPartition(var_size), 'ext4', None, 'var', p_map.partitions[-1])
var.pad_start += partition_gap  # Canibalize 1 sector from the partition to make space for the gap
var.size -= partition_gap
p_map.partitions.append(var)
```

Make sure to add the task somewhere before the volume creation.
