### ISSUE TITLE
Quickstart documentation should reference boto3

### ISSUE THREAD

**Issue by paulkmoore** [andsens/bootstrap-vz#362]
If I undertstand the recent commits correctly, there's been a migration from boto -> boto3.

The quickstart documentation still references boto, which caused a missing module error.

`ImportError: No module named boto3`

**Comment by andsens** [comment]
Good catch! Fixed :-)
@vorlock is the `boto` requirement [in setup.py](https://github.com/andsens/bootstrap-vz/blob/5bc4937704d432ac61656c4e15450a86b43a1ee9/setup.py#L26) still necessary? Doesn't everything just work with boto3 now?

**Comment by vorlock** [comment]
I'd say, yes we still need boto as I didn't port all plugins for example I didn't touch `ec2_publish`.

It shouldn't be too much work to finish it but I'll 1st try (when I have enough time) to figure out this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852449 which in theory should be fixed and that one https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853862
