### ISSUE TITLE
escaping of {foo}: possible?

### ISSUE THREAD

**Issue by indigoid** [andsens/bootstrap-vz#389]
I wanted to insert the verbatim text `${USER}` into a file via a `sed` command in the `commands` section in my manifest, without any expansion taking place.

But I don't seem to be able to escape the `{}`, and get `KeyError: USER` in the log output. Is this escaping possible? I have tried escaping with backslashes, and this did not have the desired effect.

NB: am invoking `bootstrap-vz` via `kube-deploy/imagebuilder`, but have confirmed that the Golang templating used there is not interfering. The final generated `template.yaml` contains this line:

`- [ 'chroot', '{root}', 'sed', '-i', '1i auth [success=done new_authtok_reqd=done default=die] pam_google_authenticator.so nullok user=totp secret=/efs/totp/${USER}/.google_authenticator', '/etc/pam.d/sshd' ]`

**Comment by andsens** [comment]
This is from memory, but you should be able to just use `${{USER}}`, thats the python string template way of doing things. This should probably be documented in [manifests/README.rst](https://github.com/andsens/bootstrap-vz/blob/9364b18288251abeac5e0a285694fd915dce731e/manifests/README.rst) somewhere.

**Comment by indigoid** [comment]
it certainly is. thanks!
