### ISSUE TITLE
Exception when creating an EC2 instance without cloud-init

### ISSUE THREAD

**Issue by pako-pl** [andsens/bootstrap-vz#406]
Disabling cloud-init related packages and plugin in a manifest file causes the following error:

> Traceback (most recent call last):
>   File "bootstrap-vz/bootstrap-vz", line 5, in <module>
>     main()
>   File "/home/bootstrap-vz/bootstrap-vz/bootstrapvz/base/main.py", line 29, in main
>     dry_run=opts['--dry-run'])
>   File "/home/bootstrap-vz/bootstrap-vz/bootstrapvz/base/main.py", line 111, in run
>     tasklist.run(info=bootstrap_info, dry_run=dry_run)
>   File "/home/bootstrap-vz/bootstrap-vz/bootstrapvz/base/tasklist.py", line 44, in run
>     task.run(info)
>   File "/home/bootstrap-vz/bootstrap-vz/bootstrapvz/providers/ec2/tasks/tuning.py", line 28, in run
>     copy(cloud_init_src, cloud_init_dst)
>   File "/usr/lib/python2.7/shutil.py", line 119, in copy
>     copyfile(src, dst)
>   File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
>     with open(dst, 'wb') as fdst:
> IOError: [Errno 2] No such file or directory: '/target/615ef11c/root/etc/cloud/cloud.cfg.d/01_debian_cloud.cfg'

The reason is that tuning.py tries to copy files to a non existing directory:

```
class SetCloudInitMountOptions(Task):
    description = 'Setting cloud-init default mount options'
    phase = phases.system_modification

    @classmethod
    def run(cls, info):
        cloud_init_src = os.path.join(assets, 'cloud-init/debian_cloud.cfg')
        cloud_init_dst = os.path.join(info.root, 'etc/cloud/cloud.cfg.d/01_debian_cloud.cfg')
        copy(cloud_init_src, cloud_init_dst)
        os.chmod(cloud_init_dst, 0644)
```

I was able to temporarily work around the problem by simply commenting out the last two lines from the `run` method in the `SetCloudInitMountOptions` class.

**Comment by andsens** [comment]
whoa, that task definitely belongs in the cloud-init plugin.
