### ISSUE TITLE
Should not have hardcoded urls

### ISSUE THREAD

**Issue by CMeza99** [andsens/bootstrap-vz#409]
In `bootstrapvz/common/tasks/apt.py` the security update url is hardcoded to debian.org. There may be instances where this is not desired, i.e. for compliance. This is also an unexpected behavior if one has used their internal repository in the manifest.

```python
info.source_lists.add('main', 'deb     http://security.debian.org/  {system.release}/updates ' + components)
if include_src:
    info.source_lists.add('main', 'deb-src http://security.debian.org/  {system.release}/updates ' + components)
```

**Comment by andsens** [comment]
True. I think a security mirror setting [just like the mirror setting](https://github.com/andsens/bootstrap-vz/blob/38fc7c52407d015d3c75867bfea266d0aec6d7e2/manifests/official/ec2/ebs-jessie-amd64-hvm.yml#L31) would be nice.

**Comment by CMeza99** [comment]
#415 addresses this issue. 🎉
