### ISSUE TITLE
Passwords for admin user and root should be a hash

### ISSUE THREAD

**Issue by CMeza99** [andsens/bootstrap-vz#413]
Instead of plaintext passwords in the plugins, 'admin user' and 'root password', they should be hashes. Similar to what preseed files. see https://www.debian.org/releases/stable/amd64/apbs04.html.en#preseed-account

**Comment by andsens** [comment]
Agreed. I'd be open to a PR :-)

**Comment by CMeza99** [comment]
PR #417 addresses this issue 🎉
