### ISSUE TITLE
Building image for usage on VZ and bare metal

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#419]
Hi,

we have a use case, where the image will be deployed to KVM, VMware or bare metal.
Currently we build images with provider set to kvm but they don't boot on bare metal (USB-storage, boot stuck after loading ramdisk).

What about a provider which has no vendor-specific settings, just a raw-image?

**Comment by andsens** [comment]
Hm, kvm is actually the closest you can get to a non vendor-specific setup. There's just the virtio driver, which really shouldn't get in the way of a bare-metal boot, even the kernel images are standard.  
bootstrap-vz is really made for anything *except* bare-metal, but I don't see why it wouldn't work for that env. Without an error message it's hard to say what's wrong :-/

**Comment by kevin-olbrich** [comment]
Thats the problem. There is no error message.
It shows "loading initramfs", the screen clears and then there is only a blinking cursor.
The computer can be shut down by a short press of the power button (stuck in BIOS).

**Comment by andsens** [comment]
Oh wait. In a virtualized environment you need to set the bootloader to output to the serial console so you can capture it with whatever vm you are running. You should maybe remove the ttys0 part from the grub config so you can see what is going on.
