### ISSUE TITLE
Idea: Add comment-header to files deployed by bootstrap-vz

### ISSUE THREAD

**Issue by mengelmann** [andsens/bootstrap-vz#429]
Wouldn't it be useful (appropriate?) to add specific comment-header (preamble) to files (init scripts, systemd units and other scripts) deployed by bootstrap-vz to the image, so it's clear for a user where does this file come from?

It will also make easy to find the license (just link to LICENSE in GitHub repo in the header instead of adding it to each file).

Something like that on the top of each script:

```
# This script is part of bootstrap-vz: http://github.com/andsens/bootstrap-vz
# See https://github.com/andsens/bootstrap-vz/blob/master/LICENSE for legal
# notices and disclaimers.
```

or

```
# This script has been deployed by bootstrap-vz: http://github.com/andsens/bootstrap-vz
# See https://github.com/andsens/bootstrap-vz/blob/master/LICENSE for legal
# notices and disclaimers.
```

or something similar.

What do you think?

**Comment by andsens** [comment]
Would make sense. The license part can be achieved by just using the file copying plugin. The headers could easily be added to the assets.

**Comment by mengelmann** [comment]
@andsens would you like me to prepare Pull Request for added headers to the files in assets?

I'm not sure if copying license file is required (and there is a question - where we should put it?). I would prefer to add as little files to the image as possible.

**Comment by andsens** [comment]
agreed. Skip the license file, I'd love to see the headers added though. Go for it :-)

**Comment by mengelmann** [comment]
OK, I'll take care of that.

I'll let other PR to be merged or abandoned, so there will be no conflicts.
