### ISSUE TITLE
SSH host keys are not (re)generated on Debian stretch

### ISSUE THREAD

**Issue by mengelmann** [andsens/bootstrap-vz#432]
SSH host keys are not (re)generated on Debian stretch (systemd v232-25), but they are (re)generated on Debian jessie (systemd v215-17). It means that stretch images do not have host keys except for ED25519 which are not removed due to bug #425.

I investigated and found that the issue is with LSB header in ```generate-ssh-hostkeys``` script:

```
# Default-Start:  S
```

https://github.com/andsens/bootstrap-vz/blob/master/bootstrapvz/common/assets/init.d/generate-ssh-hostkeys#L8

should be:

```
# Default-Start:  2 3 4 5
```

It's because of change introduced in systemd v231-1:

>   * Drop support for rcS.d SysV init scripts.
>    These are prone to cause dependency loops, and almost all packages with rcS scripts now ship a native systemd service.

http://metadata.ftp-master.debian.org/changelogs/main/s/systemd/systemd_232-25+deb9u1_changelog

More info on https://wiki.debian.org/Teams/pkg-systemd/rcSMigration

I'll work around this issue with PR #426 (corrected LSB header) and resolve it with PR #431 (new systemd unit) in the near future.

**Comment by andsens** [comment]
Damn @mengelmann, you're a champ. Thank you so much for your continued effort in getting this fixed!

**Comment by andsens** [comment]
Fixed with #426
