### ISSUE TITLE
How to access Grub during boot?

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#464]
Hi!

I built an image using stretch for KVM with bootloader set to grub.
**How can I access the boot menu?** I need to set some temporary kernel parameters.
Atm the menu is skipped and I am unable to use shift during boot on virt-manager.

![image](https://user-images.githubusercontent.com/503085/36849744-1ff825e2-1d65-11e8-950c-2824706f21ad.png)

Kind regards,
Kevin

**Comment by andsens** [comment]
I don't think you can, the timeout has been removed: https://github.com/andsens/bootstrap-vz/blob/a9efdb4bf94437323f00d6641f5fd8cd026564ac/bootstrapvz/common/task_groups.py#L165-L171

Here's the task that does this: https://github.com/andsens/bootstrap-vz/blob/a9efdb4bf94437323f00d6641f5fd8cd026564ac/bootstrapvz/common/tasks/grub.py#L260-L269

You should bootstrap an image where that task is not added to the tasklist.
