### ISSUE TITLE
The method driver /usr/lib/apt/methods/https could not be found

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#470]
Is it possible to include apt-transport-https in base-packages?

> Reading package lists...
> E: The method driver /usr/lib/apt/methods/https could not be found.
> E: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/stable/InRelease
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> Command 'chroot /target/8ff93316/root apt-get update' returned non-zero exit status 100
> Traceback (most recent call last):
>   File "/var/lib/jenkins/jobs/dolphin-mediasw_build_trunk/workspace/bvz-git/bootstrapvz/base/main.py", line 111, in run
>     tasklist.run(info=bootstrap_info, dry_run=dry_run)
>   File "/var/lib/jenkins/jobs/dolphin-mediasw_build_trunk/workspace/bvz-git/bootstrapvz/base/tasklist.py", line 44, in run
>     task.run(info)
>   File "/var/lib/jenkins/jobs/dolphin-mediasw_build_trunk/workspace/bvz-git/bootstrapvz/common/tasks/apt.py", line 200, in run
>     'apt-get', 'update'])
>   File "/var/lib/jenkins/jobs/dolphin-mediasw_build_trunk/workspace/bvz-git/bootstrapvz/common/tools.py", line 13, in log_check_call
>     raise e
> CalledProcessError: Command 'chroot /target/8ff93316/root apt-get update' returned non-zero exit status 100
> Rolling back

**Comment by andsens** [comment]
Yes, [see the docs](https://bootstrap-vz.readthedocs.io/en/master/manifests/index.html#bootstrapper). Add it via `bootstrapper.include_packages`
