### ISSUE TITLE
APT wants to install unneeded packages

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#478]
When installing msodbcsql17 from microsoft repo, more packages get installed which are not needed in production env:

> Executing: chroot /target/bd6f5988/root apt-get install --no-install-recommends --assume-yes sudo grub-pc linux-image-amd64 shorewall shorewall6 qemu-guest-agent icinga2 monitoring-plugins atop nload vim nano vim-nox unzip mariadb-client libmariadb-dev libmariadbclient-dev build-essential make rkhunter binutils haveged fail2ban pacemaker corosync resolvconf python3 python3-dev python3-pip python3-venv uwsgi uwsgi-plugin-python3 msodbcsql17 unixodbc unixodbc-bin unixodbc-dev freetds-dev freetds-bin tdsodbc filebeat metricbeat auditbeat heartbeat ntp openssh-server libclass-isa-perl groff-base dotnet-sdk-2.1.105 dotnet-hosting-2.0.5 dotnet-sdk-2.1.103 aspnetcore-store-2.0.3 mime-support doc-debian hdparm dotnet-sdk-2.1.200 gettext-base **dotnet-sdk-2.1.300-preview2-008533** libpam-systemd man-db ucf debian-faq krb5-locales xz-utils dbus ncurses-term liblockfile-bin dotnet-sdk-2.1.4 dotnet-hosting-2.0.7 dotnet-hosting-2.0.6 less aspnetcore-store-2.0.8 dotnet-hosting-2.0.4 libswitch-perl apt-listchanges python3-reportbug gpgv1 dotnet-hosting-2.0.8 aspnetcore-store-2.0.7 bind9-host reportbug **aspnetcore-runtime-2.1.0-preview2-final** bzip2 perl **dotnet-sdk-2.0.0** manpages wamerican dotnet-sdk-2.1.201 openssh-client gnupg1 aspnetcore-runtime-2.1.0-rc1-final file python-minimal dotnet-sdk-2.0.3 bash-completion perl-modules-5.24 aspnetcore-store-2.0.6 python dotnet-sdk-2.0.2 python2.7 dotnet-sdk-2.1.2 dotnet-sdk-2.1.104 aspnetcore-runtime-2.1 netcat-traditional telnet traceroute dotnet-sdk-2.1.101 pciutils aspnetcore-store-2.0.5 lsof aspnetcore-store-2.0.0 dotnet-sdk-2.1.3 dotnet-hosting-2.0.3 dotnet-sdk-2.1.300-rc1-008673 dotnet-sdk-2.1 aspnetcore-runtime-2.1.0-preview1-final dotnet-hosting-2.0.0

Some examples are marked. Where are these packages added to the list? Which task adds those?

**Comment by kevin-olbrich** [comment]
This is an issue with:
`install_standard: true`

Microsoft marks it's packages as "standard".

Is it possible to install "install_standard" packages before adding 3rd party repositories?

**Comment by andsens** [comment]
what the hell? No. Just no, Microsoft shouldn't mark their packages as "standard", this is plain wrong.  
This doesn't seem like a problem with bootstrap-vz to me. @CMeza99, what do you think? (btw. is it ok I mention you in some of the issues where I need help?)

**Comment by kevin-olbrich** [comment]
After further analysis I agree with you 100%.
Sadly I did not find any way to contact MS as comments are closed, the docs repo does not allow issues and there is no contact email.

**Comment by CMeza99** [comment]
I would like that the packages that I expecting to install are the ones that get installed. I.e, so if I have added a different build, version, etc of a package that one is the one that gets installed from the beginning. As already stated, MS has packaged their software in a way that does not conform to standards. To workaround 3rd party issues, I think a plugin may be the best solution at the moment. :(

@andsens It is not a problem to @ me, I'm glad to help where I can :)
And since we seem to be in agreement (more or less) can we close the issue? :)

**Comment by andsens** [comment]
@CMeza99, good to know :-)

Yeah, lets close it.
