### ISSUE TITLE
cloud-init overwrites default locale

### ISSUE THREAD

**Issue by andsens** [andsens/bootstrap-vz#58]
@oddysey4me is reporting in #49 that the default locale is overwritten by cloud-init on boot. The cloud-init plugin should match the default locale setting of cloud-init to the one that is set in the manifest.

**Comment by andsens** [comment]
Is this issue still present? And is it something we can do anything about in bootstrap-vz?

**Comment by drywheat** [comment]
I haven't had an issue with this since way back when.

**Comment by andsens** [comment]
OK, marking it has fixed then :-)
