### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Rory-Finnegan** [andsens/bootstrap-vz#74]
It would be nice to have some basic tests to make sure I'm not breaking anything when I make changes, possibly setup with tox or travis-ci.  I could probably get started on this, but any suggestions on prioritization would be helpful.

**Comment by myhro** [comment]
Fixed in dev when [`wip-integration-testing` was merged into `development`](https://lists.debian.org/debian-cloud/2015/04/msg00039.html).

**Comment by Rory-Finnegan** [comment]
Awesome, thanks for all your hard work on this! :-)

**Comment by myhro** [comment]
Rory,

Kudos to Anders, as we can say that he pretty much did everything by himself. :-)

**Comment by andsens** [comment]
*Takes a bow*
Hehe, thank you :-)

It took a while, but I really think it paid off. Now we have a base we can build on. 
Connecting to the instance via SSH etc. is next, but all in due time :-)
