### ISSUE TITLE
Load stand-alone plugins

### ISSUE THREAD

**Issue by myhro** [andsens/bootstrap-vz#98]
How can we load third-party plugins which are not part of the main bootstrap-vz repository? Anders and I have [discussed that in the beginning of the past month](https://github.com/andsens/bootstrap-vz/commit/33a430566b603f34e73e5be462822916e018283c#commitcomment-5901496), although I haven't yet looked at how they are currently being loaded. It would be nice if the plugins could be just proper python packages.

**Comment by andsens** [comment]
Fixed with only 21 lines of code :-)

**Comment by andsens** [comment]
Oh, and the docs are [here](http://bootstrap-vz.readthedocs.org/en/master/developers/plugins.html).

**Comment by myhro** [comment]
Nicely done, Anders! The docs are also pretty comprehensive. :-)
